### ISSUE TITLE
my template does not work any more

### ISSUE THREAD

**Issue by behrica** [seancorfield/clj-new#76]
Running this:

```
clj  -A:project/new :template clj-py-r-template/clj-template  :name me/my-app
```

fails with a longuish weird exception:

```
Exception in thread "DefaultMetadataResolver-0-0" java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme name at index 0: :template/clj-template/maven-metadata.xml
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:109)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.getLocation(Maven2RepositoryLayoutFactory.java:159)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:221)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:588)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.URISyntaxException: Expected scheme name at index 0: :template/clj-template/maven-metadata.xml
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
	at java.base/java.net.URI$Parser.parse(URI.java:3108)
	at java.base/java.net.URI.<init>(URI.java:685)
	at java.base/java.net.URI.<init>(URI.java:786)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:105)
	... 7 more
Exception in thread "DefaultMetadataResolver-0-1" java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme name at index 0: :template/clj-template/maven-metadata.xml
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:109)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.getLocation(Maven2RepositoryLayoutFactory.java:159)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:221)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:588)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.URISyntaxException: Expected scheme name at index 0: :template/clj-template/maven-metadata.xml
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
	at java.base/java.net.URI$Parser.parse(URI.java:3108)
	at java.base/java.net.URI.<init>(URI.java:685)
	at java.base/java.net.URI.<init>(URI.java:786)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:105)
	... 7 more
Exception in thread "DefaultMetadataResolver-1-0" java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme name at index 0: :template/boot-template/maven-metadata.xml
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:109)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.getLocation(Maven2RepositoryLayoutFactory.java:159)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:221)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:588)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.URISyntaxException: Expected scheme name at index 0: :template/boot-template/maven-metadata.xml
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
	at java.base/java.net.URI$Parser.parse(URI.java:3108)
	at java.base/java.net.URI.<init>(URI.java:685)
	at java.base/java.net.URI.<init>(URI.java:786)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:105)
	... 7 more
Exception in thread "DefaultMetadataResolver-1-1" java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme name at index 0: :template/boot-template/maven-metadata.xml
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:109)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.getLocation(Maven2RepositoryLayoutFactory.java:159)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:221)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:588)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.URISyntaxException: Expected scheme name at index 0: :template/boot-template/maven-metadata.xml
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
	at java.base/java.net.URI$Parser.parse(URI.java:3108)
	at java.base/java.net.URI.<init>(URI.java:685)
	at java.base/java.net.URI.<init>(URI.java:786)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:105)
	... 7 more
Exception in thread "DefaultMetadataResolver-2-1" java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme name at index 0: :template/lein-template/maven-metadata.xml

	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:109)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.getLocation(Maven2RepositoryLayoutFactory.java:159)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:221)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:588)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.URISyntaxException: Expected scheme name at index 0: :template/lein-template/maven-metadata.xml
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
	at java.base/java.net.URI$Parser.parse(URI.java:3108)
	at java.base/java.net.URI.<init>(URI.java:685)
	at java.base/java.net.URI.<init>(URI.java:786)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:105)
	... 7 more
Failed with: java.net.URISyntaxException: Expected scheme name at index 0: :template/lein-template/maven-metadata.xml
Exception in thread "DefaultMetadataResolver-2-0" java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme name at index 0: :template/lein-template/maven-metadata.xml
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:109)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.getLocation(Maven2RepositoryLayoutFactory.java:159)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:221)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:588)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.URISyntaxException: Expected scheme name at index 0: :template/lein-template/maven-metadata.xml
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
	at java.base/java.net.URI$Parser.parse(URI.java:3108)
	at java.base/java.net.URI.<init>(URI.java:685)
	at java.base/java.net.URI.<init>(URI.java:786)
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayout.toUri(Maven2RepositoryLayoutFactory.java:105)
	... 7 more
Execution error (ExceptionInfo) at clj-new.helpers/resolve-remote-template (helpers.clj:171).
Could not load artifact for template: :template
	Tried coordinates:
		[:template/boot-template "RELEASE"]
		[:template/lein-template "RELEASE"]

For more detail, enable verbose logging with :verbose 1, 2, or 3 
```

**Comment by behrica** [comment]
the alias 'project/new' for me is

```
 :project/new
  {:replace-deps {com.github.seancorfield/clj-new {:mvn/version "1.1.331"}}
   :exec-fn      clj-new/create
   :exec-args    {:template lib :name practicalli/playground}
   :main-opts    ["-m" "clj-new.create"]}
```

**Comment by behrica** [comment]
It does work like this:

```
clj  -A:project/new clj-py-r-template behrica/test
```

which I do not understand

**Comment by behrica** [comment]
Solved. I always used wromg syntax.
I made PR to clarify it: #77
